### ISSUE TITLE
Bluetooth running in background even if the user closes the app

### ISSUE THREAD

**Issue by keniobats** [halilkabaca/NovarumBluetooth#2]
The main idea of this is to be able to connect the smartphone to special devices that need to keep the connection alive.

**Comment by halilkabaca** [comment]
Hi,
Thank you for your interest in Novarum Bluetooth Module. On the latest version you can now start bluetooth connection as a background service and it will be kept alive even the app is not running. But to get the data when the app is not running you have to check for activity intent as we start the main application activity again. You can check the example application for the details. Please let me know if you encounter any problems.

Thank you for your support.
Halil
