### ISSUE TITLE
sendData running as service.

### ISSUE THREAD

**Issue by skaflux** [halilkabaca/NovarumBluetooth#3]
First, Thanks!
When enabling running as a service I can receive data but when I attempt to sendData I get an error. Isconnected returns true so I guess it is that the btsocket is null. Do I need an extra step or is it a feature not yet supported?

**Comment by halilkabaca** [comment]
Hello,
Thank you for your interest in Novarum Bluetooth Module.
Background service is initially implemented only to receive data but sending part is easy, i will update the code to reflect the changes and let you know again.

Thank you for the heads up
Halil

**Comment by halilkabaca** [comment]
Hello again,
I tried to make a quick fix could you try and let me know if it works?

Regards
Halil

**Comment by skaflux** [comment]
Thanks. I'll try it out later today and let you know.

**Comment by skaflux** [comment]
It Works!

Some extra comments:
1. When receiving a message as a service, would it be better to have just a
notification in the status bar rather than automatically opening the app?
I've been testing on a Galaxy S3 and Note II.

Thank You!

On Mon, May 12, 2014 at 9:36 AM, Kelvin Ruiz skaflux@gmail.com wrote:

> Thanks. I'll try it out later today and let you know.
> On May 12, 2014 9:10 AM, "Halil" notifications@github.com wrote:
> 
> > Hello again,
> > I tried to make a quick fix could you try and let me know if it works?
> > 
> > Regards
> > Halil
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/halilkabaca/NovarumBluetooth/issues/3#issuecomment-42829505
> > .

## 

Kelvin Ruiz

**Comment by halilkabaca** [comment]
Opening the app and sending data with the intent was the best idea i could come up with. Maybe i can create a function to trigger another Titanium service or as you suggested send it as a notification but i don't think this would be useful for most of the use cases. Any suggestions are welcome :)

**Comment by skaflux** [comment]
Halil,

Of course the assumption is that an external bluetooth device is on before
calling searchDevices(). However if none are found there's no way to get
the timeout event.

Could you add a method for cancelDiscovery() or an event for
ACTION_DISCOVERY_FINISHED that should fire after 12 seconds if no devices
are found?

Thanks!

On Tue, May 13, 2014 at 3:57 AM, Halil notifications@github.com wrote:

> Opening the app and sending data with the intent was the best idea i could
> come up with. Maybe i can create a function to trigger another Titanium
> service or as you suggested send it as a notification but i don't think
> this would be useful for most of the use cases. Any suggestions are welcome
> :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/halilkabaca/NovarumBluetooth/issues/3#issuecomment-42927266
> .

## 

Kelvin Ruiz
